name: r2s mininal

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/r2s_mininal.yml'
      - 'config_rk3328'
  schedule:
    - cron: '09 08 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          sudo apt-get update
          sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash

      - name: Install Repo
        run: |
          rm -rf repo
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
          rm -rf repo

      - name: Init Source
        run: |
          rm -rf friendlywrt-rk3328
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328
          repo init -u https://github.com/fanck0605/friendlywrt_manifests -b master-v19.07.1 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
          repo sync -c --no-clone-bundle -j8

      - name: Custom Configure Files
        run: |
          cp config_rk3328 friendlywrt-rk3328/configs/config_rk3328

      - name: Build FriendlyWrt
        run: |
          cd friendlywrt-rk3328
          ./build.sh nanopi_r2s.mk

      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          gzip friendlywrt-rk3328/out/*.img
          cp friendlywrt-rk3328/out/*.img* ./artifact/

      - name: Save configs
        run: |
          cd friendlywrt-rk3328/friendlywrt
          ./scripts/diffconfig.sh > ../../artifact/config-lite
          cp .config ../../artifact/config-full

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: R2S-Minimal
          path: ./artifact/
